import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { getServiceSupabase } from '@/lib/supabase/service-role'
import { hashToken } from '@/lib/auth/tokens'

/**
 * Endpoint for Institution Admin account activation using an invite token generated by platform owner.
 */
export async function POST(request: Request) {
  try {
    const { token, email, password, fullName } = await request.json()

    if (!token || !email || !password || !fullName) {
      return NextResponse.json(
        { error: 'Activation token, email, password, and full name are required' },
        { status: 400 }
      )
    }

    const tokenHash = hashToken(token.trim())
    const serviceClient = getServiceSupabase()

    // 1. Verify activation invite
    const { data: invite, error: inviteErr } = await serviceClient
      .from('invites')
      .select('*, institutions(name)')
      .eq('token_hash', tokenHash)
      .single()

    if (inviteErr || !invite) {
      return NextResponse.json(
        { error: 'Invalid or unrecognized admin activation token' },
        { status: 404 }
      )
    }

    if (invite.used_at) {
      return NextResponse.json(
        { error: 'This admin activation token has already been used' },
        { status: 410 }
      )
    }

    if (new Date(invite.expires_at) < new Date()) {
      return NextResponse.json(
        { error: 'This admin activation token has expired' },
        { status: 410 }
      )
    }

    if (invite.role !== 'institution_admin' && invite.role !== 'platform_owner') {
      return NextResponse.json(
        { error: 'This token is not authorized for institution administrator activation' },
        { status: 403 }
      )
    }

    // 2. Create user with Supabase Auth
    const supabase = await createClient()
    const { data: authData, error: authErr } = await supabase.auth.signUp({
      email,
      password,
      options: {
        data: { full_name: fullName },
      },
    })

    if (authErr || !authData.user) {
      return NextResponse.json(
        { error: authErr?.message || 'Failed to initialize administrator user account' },
        { status: 400 }
      )
    }

    // 3. Upsert profile as institution_admin
    const { error: profileErr } = await serviceClient
      .from('profiles')
      .upsert({
        id: authData.user.id,
        institution_id: invite.institution_id,
        full_name: fullName,
        email,
        role: invite.role as 'institution_admin' | 'platform_owner',
        organizer_approval_status: 'approved',
        updated_at: new Date().toISOString(),
      })

    if (profileErr) {
      return NextResponse.json(
        { error: `User created but failed to configure admin profile: ${profileErr.message}` },
        { status: 500 }
      )
    }

    // 4. Mark invite as used
    await serviceClient
      .from('invites')
      .update({ used_at: new Date().toISOString() })
      .eq('id', invite.id)

    return NextResponse.json({
      success: true,
      message: 'Institution administrator account activated successfully',
      destination: '/admin',
    })
  } catch (err: any) {
    return NextResponse.json(
      { error: err.message || 'Internal server error' },
      { status: 500 }
    )
  }
}
